name: "Podcast Generator"
author: "Sachin Sharma"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: Ths committer's name
    required: true
    default: ${{ github.actor }}
